server:
  port: 19000 #工程端口
logging:
    level:
      root: info
    file:
      path: poker-im/log
open:
  ai:
    apiBaseUrl: https://api.openai.com
    authorization: Bearer xxxxxxxxxxxxxxx
spring:
  main:
    allow-circular-references: true
  application:
    name: poker-im
  redis:
    host: 192.168.117.200
    port: 63790
    password:
    database: 10
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: true
        group: spring-cloud
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    protocol: nacos
    address: nacos://127.0.0.1:8848
    group: dubbo
  cloud:
    subscribed-services: poker-user