server:
  port: 22000 #工程端口
logging:
    level:
      root: info
    file:
      path: poker-dz/log
spring:
  application:
    name: poker-dz
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: true
        group: spring-cloud